# Generated by Django 3.1.4 on 2021-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210104_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
