# Generated by Django 3.1.4 on 2021-01-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow_is_followed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='unlike',
            new_name='like',
        ),
    ]
